### ISSUE TITLE
Need support for filesize upto 2gb

### ISSUE THREAD

**Issue by rsoorajs** [tjtanjin/simple-media-converter#3]
can you add filesize support upto 2gb ?

you have to use app id and api hash for this,
also you can use 'python telegram bot or telethon  or pyrogram' frameworks for make this easy...

Your bot is awsome,just need to increase the filesize limitation.thats all

Thanks in advance

**Comment by tjtanjin** [comment]
Just to give an update I will unlikely be able to address this issue anytime soon :( I most definitely welcome pull requests for this but otherwise I will keep this open and revisit this hopefully by sometime mid-year ;-;
