### ISSUE TITLE
File too large 

### ISSUE THREAD

**Issue by linkvapeluckyman** [tjtanjin/simple-media-converter#6]
I am trying to convert 1gb mkv to mp4, showing - file too large, how to increase size limitation?
I have good server to process big files

**Comment by tjtanjin** [comment]
Hey! Apologies for getting back late. The file size limit is imposed by telegram. However, you may set up your own [Telegram Bot API](https://github.com/tdlib/telegram-bot-api#switching) server to have a higher limit of 2GB.
